In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])

In [3]:
arr


array([1, 2, 3])

In [4]:
len(arr)

3

In [5]:
arr[2]

3

In [6]:
type(arr[2])

numpy.int32

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr32=np.array([1,2,3],dtype=np.int32)

In [9]:
arr32

array([1, 2, 3])

In [10]:
arr64=np.array([1,2,3],dtype=np.int64)
arr64

array([1, 2, 3], dtype=int64)

In [11]:
arr*arr

array([1, 4, 9])

In [12]:
v1=np.random.rand(1000000)
v2=np.random.rand(1000000)

In [13]:
v1

array([ 0.57891943,  0.55011777,  0.75667873, ...,  0.70788574,
        0.39594037,  0.46384424])

In [14]:
v2

array([ 0.87308918,  0.34357747,  0.87301719, ...,  0.67607492,
        0.99445331,  0.04531092])

In [15]:
v1*v2

array([ 0.50544829,  0.18900807,  0.66059354, ...,  0.4785838 ,
        0.39374422,  0.02101721])

In [16]:
%time v1*v2

Wall time: 0 ns


array([ 0.50544829,  0.18900807,  0.66059354, ...,  0.4785838 ,
        0.39374422,  0.02101721])

In [17]:
#to get the dot prod
np.dot(arr,arr)

14

In [18]:
arr@arr

14

In [19]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
v=np.arange(12)

In [21]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
#v.reshape((4,3))
v.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
mat=np.arange(12).reshape((4,3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
mat.shape

(4, 3)

In [25]:
mat2=mat.reshape((3,4))
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
#changing a value at second row and third column----notice how both mat and mat2 get changed
mat[1,2]=17

In [27]:
mat

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
mat2


array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
#to transpose a matrix
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

In [30]:
mat

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])