In [6]:
import numpy as np

In [7]:
arr=np.array([1,2,3])

In [8]:
arr


array([1, 2, 3])

In [9]:
len(arr)

3

In [10]:
arr[2]

3

In [11]:
type(arr[2])

numpy.int32

In [12]:
arr.dtype

dtype('int32')

In [13]:
arr32=np.array([1,2,3],dtype=np.int32)

In [14]:
arr32

array([1, 2, 3])

In [15]:
arr64=np.array([1,2,3],dtype=np.int64)
arr64

array([1, 2, 3], dtype=int64)

In [16]:
arr*arr

array([1, 4, 9])

In [17]:
v1=np.random.rand(1000000)
v2=np.random.rand(1000000)

In [18]:
v1

array([ 0.9900412 ,  0.10052528,  0.29104486, ...,  0.60882566,
        0.71991939,  0.12074757])

In [19]:
v2

array([ 0.27080023,  0.33700408,  0.61633295, ...,  0.6217733 ,
        0.45696554,  0.03552498])

In [20]:
v1*v2

array([ 0.26810339,  0.03387743,  0.17938054, ...,  0.37855154,
        0.32897835,  0.00428955])

In [21]:
%time v1*v2

Wall time: 0 ns


array([ 0.26810339,  0.03387743,  0.17938054, ...,  0.37855154,
        0.32897835,  0.00428955])

In [22]:
#to get the dot prod
np.dot(arr,arr)

14

In [23]:
arr@arr

14

In [24]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
v=np.arange(12)

In [26]:
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
#v.reshape((4,3))
v.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
mat=np.arange(12).reshape((4,3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
mat.shape

(4, 3)

In [30]:
mat2=mat.reshape((3,4))
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
#changing a value at second row and third column----notice how both mat and mat2 get changed
mat[1,2]=17

In [32]:
mat

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
mat2


array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
#to transpose a matrix
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

In [35]:
mat

array([[ 0,  1,  2],
       [ 3,  4, 17],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
#Slicing
nums=[1,2,3,4,5]
nums[2:5]

[3, 4, 5]

In [37]:
v=np.arange(1,6)
v[2:4]

array([3, 4])

In [38]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
#to get a particular row
arr[0]

array([0, 1, 2, 3])

In [40]:
#to get second row, second column
arr[1][1]

5

In [41]:
#to pick every row, and then the second element of every row
arr[:,1]

array([1, 5, 9])

In [42]:
arr[:,1].reshape(3,1)

array([[1],
       [5],
       [9]])

In [43]:
#slicing can be used on both axes
arr[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [44]:
#can be used to set values as well--this is broadcasting --setting the scalar
arr[1:,2:]=7

In [45]:
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

In [46]:
#boolean indexing
#in order to select parts of an array that satisfy some threshold
arr=np.arange(3)
arr[np.array([True,False,True])]

array([0, 2])

In [47]:
arr>=1

array([False,  True,  True], dtype=bool)

In [48]:
arr

array([0, 1, 2])

In [49]:
arr=np.arange(10)

In [50]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [52]:
arr[(arr>7)|(arr<2)]

array([0, 1, 8, 9])

In [53]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
#understanding broadcasting

In [58]:
arr=np.arange(3)
print(arr)

[0 1 2]


In [60]:
arr+4
#scalar to vector--adds the scalar to every element of array

array([4, 5, 6])

In [61]:
arr / 7

array([ 0.        ,  0.14285714,  0.28571429])

In [62]:
arr**2

array([0, 1, 4])

In [63]:
#let's create a matrix of 3 by 3
mat=np.arange(9).reshape([3,3])

In [64]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
#let's create a vector of 3
vec=np.arange(3)
vec

array([0, 1, 2])

In [67]:
mat+vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [73]:
v1=np.arange(3)
v2=np.arange(3).reshape((3,1))

In [69]:
v2

array([[0],
       [1],
       [2]])

In [82]:
#dir(v2)

In [75]:
v2.shape

(3, 1)

In [76]:
v1

array([0, 1, 2])

In [83]:
v2


array([[0],
       [1],
       [2]])

In [80]:
v1.shape,v2.shape


((3,), (3, 1))

In [85]:
v1+v2
#v1 will be extended down and v2 will be extended to a row of zeroes,to a row of 1's and to a row of 2's
#see the video snippet at 2:30 of 'Understanding broadcasting'

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [84]:
#np always tries to find out the best match
np.arange(3)+np.arange(4)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [86]:
#understanding array operations
v=np.arange(12).reshape(4,3)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [87]:
#to view the attributes and methods of v; note that attributes that start with 2 underscore have a special meaning, they are
#called dunder methods, meaning double underscore
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 

In [88]:
#when i type v dot and hit enter, jupyter won't show me the dunder methods


In [89]:
#to do the transpose,use
v.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [91]:
#even if  one element is true
v.any()

True

In [92]:
#return true if all element are true
v.all()

False

In [93]:
if v:
    print("v is true")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [94]:
#to get the zen of python
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [95]:
#since first element is 0, we get the prod as 0
v.prod()

0

In [96]:
#to work row-wise, sums 
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [97]:
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [99]:
#to get the sum of each column
v.sum(axis=0)

array([18, 22, 26])

In [100]:
#to mutate the array, w/o affecting the original one
v1=v.copy()

In [101]:
v1[0,0]=1000

In [102]:
v1

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [103]:
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [107]:
#methods for serialization, send an array over a socket to be written to a file or DB for later retrieval
#we use python's pickle protocol
data=v.dumps()
data


b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X0\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [108]:
type(data)
#observe that is a stream of bytes

bytes

In [109]:
v2=np.loads(data)

In [110]:
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [111]:
#instead of v.prod , we can also call the prod on the np module
np.prod(v)

0

In [112]:
#understanding ufuncs--universal functions
np.sin(np.pi/2)
#note that sin expects inout in radians

1.0

In [113]:
#why numpy bothers to define a function that is already defined in python
v=np.arange(-3,3)
#now we can call numpy.sin on the vector itself
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [114]:
#ufuncs are universal functions --mening they can work on both scalars(plane numbers) and arrays
#take an example-
def noneg(num):
    if num<0:
        return 0
    return num


In [115]:
noneg(-13)

0

In [116]:
noneg(13)

13

In [117]:
v

array([-3, -2, -1,  0,  1,  2])

In [118]:
noneg(v)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [119]:
#to avoid this we use decorators
#decorators are functions that use functions as arguments and return functions
#whenever you see me writing @np.vectorize, and then the definition of noneg===>this is very much like writing the definition
# noneg and then saying that noneg is equal to np.vectorize of noneg

In [120]:
@np.vectorize
def noneg(num):
    if num<0:
        return 0
    return num

In [121]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [122]:
#the above s equal to below
def noneg(num):
    if num<0:
        return 0
    return num
noneg=np.vectorize(noneg)


In [123]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [124]:
noneg(3)

array(3)

In [125]:
noneg(3).shape

()

In [126]:
#so the function now works on both scalar and vector

In [127]:
np.nan

nan

In [ ]:
#Pandas
#numpy is great for working with matrices of the same type(integers,floats etc.
#but data in the real world is often composed of mixed types--heterogenous data
#pandas support mixed types with ease
